services:
  ingest:
    build:
      context: ../..
      dockerfile: .infra/ingestor/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - ../../data:/app/data
      - ../../chroma_db:/app/chroma_db
    restart: "no"
